### ISSUE TITLE
Able to use Vault Fruit After Boss is Defeated 

### ISSUE THREAD

**Issue by Euroam** [Iskallia/Vault-public-S1#111]
After defeating the boss in the Vault, I was able to eat Vault Fruits, Increasing the timer from the 20 seconds countdown. This is very op because the vault mobs cannot damage you after defeating the boss and you are going to have a free run from all the mobs and if you are running an omega vault it pretty much means you can get a lot of artifacts if you gather enough fruits.

1.Enter and Defeat the Boss 
2.Eat Vault Fruits

**Expected behavior**
The Vault Fruit Should be Disabled from eating like in the overworld

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version : 1.0.1

I was Testing the damage and gear i have to use to run the vaults in creative btw

**Comment by iGoodie** [comment]
Oh, that's a smart one!
Thanks for letting us know, we'll be fixing it in the next versions :)
